### ISSUE TITLE
fix:時刻表のpdfに遷移できない

### ISSUE THREAD

**Issue by PoPodada** [ichidaisai/2024.ichidaisai.com#146]
- アクセスページのpdfはこちらからのところを押しても遷移できず
- エラーが出てしまうため修正

**Comment by cldbzl** [comment]
https://drive.google.com/file/d/1aCtsAo3_g0QMRh1O9Qx5gAvGZumN75Qo/view?usp=sharing　に飛ぶようにしちゃだめですか…
