### ISSUE TITLE
「アクセス」ページ作成

### ISSUE THREAD

**Issue by cldbzl** [ichidaisai/2024.ichidaisai.com#65]
広島市立大学へのアクセス方法と地図．昨年のウェブサイトを参考にすること．
[2023年度](https://2023.ichidaisai.com/access)

## テキスト例

> 【アストラムライン】大塚駅下車 徒歩２５分
【バス】広島バスセンターより２番乗り場「くすの木台」「市立大学前」下車
４番乗り場「花の季台・こころ西風梅苑・こころ産業団地・こころ南中央」方面行き「沼田料金所前(※)」下車 徒歩８分
※「市立大学前」に止まる便もございます。

**Comment by PoPodada** [comment]
吉田君担当
