### ISSUE TITLE
HOMEに文章とPDFファイルを追加

### ISSUE THREAD

**Issue by cldbzl** [ichidaisai/2024.ichidaisai.com#79]
注意事項の下に以下の文章を追加

 _【重要なお知らせ】
大学祭当日は、駐車場の混雑が予想されます。
一般来場者の皆様には、できるだけバスなどの公共交通機関をご利用いただくようお願い申し上げます。

バスの増便に関する詳しい情報は、以下の資料をご覧ください。_

増便の資料(2024102627)はpictureに入っています

**Comment by hina81** [comment]
<img width="1433" alt="スクリーンショット 2024-10-10 10 07 57" src="https://github.com/user-attachments/assets/d1a3022b-fca7-48e3-b06c-b4b45d292e24">
